author = "Hugo Grochau"
baseurl = "http://hugo.grochau.com/"
builddrafts = true
canonifyurls = true
contentdir = "content"
disqusshortname = ""
enableEmoji = true
languageCode = "en-US"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
theme = "cocoa-eh"
title = "Hugo Grochau"
[params]
dateform = "Jan 2006"
dateformfull = "Mon Jan 2 2006"
description = "Hugo Grochau"
email = "hugo@grochau.com"
faviconfile = "img/profile.jpg"
github = "hugogrochau"
highlightjs = true
lang = "en"
linkedin = "hugogrochau"
logofile = "img/profile.jpg"
goodreads = "hugogrochau"
keybase = "hugogrochau"
[permalinks]
blog = "blog/:slug/"
