baseurl = "https://hugo.grochau.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Hugo Grochau"
title = "Hugo Grochau"
disqusshortname = ""
pluralizelisttitles = false
enableEmoji = true

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Hugo Grochau"
logofile = "img/profile.jpg"
faviconfile = "img/profile.jpg"
highlightjs = true
lang = "en"
github = "//github.com/hugogrochau"
email = "hugo@grochau.com"
linkedin = "//www.linkedin.com/in/hugogrochau"
twitter = "//twitter.com/hugogrochau"
