name = "hugo-grochau-com"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-namespace-preview-id"

[vars]
ENVIRONMENT = "production"

[env.staging]
name = "hugo-grochau-com-staging"
vars = { ENVIRONMENT = "staging" }

# Uncomment and configure if you need custom domains
# [env.production]
# routes = [
#   { pattern = "hugo.grochau.com/*", zone_name = "grochau.com" },
#   { pattern = "www.hugo.grochau.com/*", zone_name = "grochau.com" }
# ]
